# First Excersice In Tensorflow

## Importation des Packages

In [3]:
import tensorflow as tf
from tensorflow import keras
import numpy as np

In [9]:
tf.__version__

'2.6.2'

## Création du mlodèles

In [4]:
model = keras.Sequential(
  [
      keras.layers.Dense( units=1, input_shape=[1] )
  ]
)
model.compile( 
    optimizer='sgd',
    loss = 'mean_squared_error'
)

## Entrainement du modèle

In [6]:
xs = np.array([-1.0, 0.0, 1.0, 2.0, 3.0, 4.0], dtype=np.float)
ys = np.array([-3.0, -1.0, 1.0, 3.0, 5.0, 7.0], dtype=np.float)

model.fit(xs, ys, epochs=50)

Epoch 1/50
1/1 [==============================] - 0s 379ms/step - loss: 13.6128
Epoch 2/50
1/1 [==============================] - 0s 16ms/step - loss: 10.9423
Epoch 3/50
1/1 [==============================] - 0s 8ms/step - loss: 8.8366
Epoch 4/50
1/1 [==============================] - 0s 11ms/step - loss: 7.1752
Epoch 5/50
1/1 [==============================] - 0s 5ms/step - loss: 5.8635
Epoch 6/50
1/1 [==============================] - 0s 3ms/step - loss: 4.8271
Epoch 7/50
1/1 [==============================] - 0s 10ms/step - loss: 4.0072
Epoch 8/50
1/1 [==============================] - 0s 7ms/step - loss: 3.3579
Epoch 9/50
1/1 [==============================] - 0s 3ms/step - loss: 2.8429
Epoch 10/50
1/1 [==============================] - 0s 9ms/step - loss: 2.4335
Epoch 11/50
1/1 [==============================] - 0s 6ms/step - loss: 2.1074
Epoch 12/50
1/1 [==============================] - 0s 5ms/step - loss: 1.8469
Epoch 13/50
1/1 [==============================] - 0s 7ms/step - l

In [8]:
model.predict(np.array([-2]))

array([[-3.5695734]], dtype=float32)

In [10]:
model.predict(np.array([10]))

array([[17.036669]], dtype=float32)

In [16]:
bed_rooms = np.array([i for i in range(1, 8)], dtype=np.float)
bed_rooms    

array([1., 2., 3., 4., 5., 6., 7.])

In [21]:
xs = np.array(bed_rooms, dtype=np.float)
ys = [ (rooms*50 + 50)  for rooms in xs ]

In [23]:
ys

[100.0, 150.0, 200.0, 250.0, 300.0, 350.0, 400.0]

In [26]:
def house_model():
    ### START CODE HERE
    bed_rooms = [i for i in range(1, 8)]
    
    # Define input and output tensors with the values for houses with 1 up to 6 bedrooms
    # Hint: Remember to explictly set the dtype as float
    xs = np.array(bed_rooms, dtype=float)
    ys = np.array([(rooms*50 + 50)  for rooms in xs], dtype=float)
    
    # Define your model (should be a model with 1 dense layer and 1 unit)
    model = keras.Sequential([
        keras.layers.Dense(units=1, input_shape=[1])
    ])
    
    # Compile your model
    # Set the optimizer to Stochastic Gradient Descent
    # and use Mean Squared Error as the loss function
    model.compile(optimizer='sgd', loss='mean_squared_error')
    
    # Train your model for 1000 epochs by feeding the i/o tensors
    model.fit(xs, ys, epochs=1000)
    
    ### END CODE HERE
    return model

In [27]:
model = house_model()

Epoch 1/1000
1/1 [==============================] - 0s 273ms/step - loss: 68750.0391
Epoch 2/1000
1/1 [==============================] - 0s 5ms/step - loss: 23629.8125
Epoch 3/1000
1/1 [==============================] - 0s 6ms/step - loss: 8247.9805
Epoch 4/1000
1/1 [==============================] - 0s 5ms/step - loss: 3003.2200
Epoch 5/1000
1/1 [==============================] - 0s 5ms/step - loss: 1213.9445
Epoch 6/1000
1/1 [==============================] - 0s 9ms/step - loss: 602.5651
Epoch 7/1000
1/1 [==============================] - 0s 4ms/step - loss: 392.7134
Epoch 8/1000
1/1 [==============================] - 0s 3ms/step - loss: 319.7423
Epoch 9/1000
1/1 [==============================] - 0s 3ms/step - loss: 293.4418
Epoch 10/1000
1/1 [==============================] - 0s 9ms/step - loss: 283.0610
Epoch 11/1000
1/1 [==============================] - 0s 4ms/step - loss: 278.1180
Epoch 12/1000
1/1 [==============================] - 0s 5ms/step - loss: 275.0389
Epoch 13/1000
1/